### ISSUE TITLE
Refactor NFT metadata (image in IPFS and ICP)

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#16]
**ToDo**

- [x] add libraries for IPFS
- [x] Add IPFS variables in env
- [x] Add async persistence of photo and metadata in IPFS
- [x] Add IPFS links in NFT API
- [x] Add IPFS link fields in bdd
- [x] Add ICP logic to upload images

**Comment by dappsar** [comment]
Identificar una estrategia para que del front se pueda obtener:
- Un user que tiene un NFT "original", que pueda visualizar qué copias tiene con orden de "copiado" (orden de llegada)
- Un user que tiene un NFT "copia", que pueda saber cuál es el NFT "original".

La idea es dejar esa relación en bdd para que sea de fácil acceso desde front.

**Comment by dappsar** [comment]
Al crear un NFT, se completan los campos como se realiza hoy, sin cambios.

Al crar una copia, se completan los campos como se realiza hoy, añadiendo uno más
- original_id: con el id del NFT original.

Ejemplo: NFT original #1:

```json
{
  "id": 1, 
  [...]
}
```

Cuando copian el NFT original #1

```json
{
  "id": 27, // NFT_ID
  "copy_of": 1
  [...]
}
```

Cuando copian el NFT #27 (que es una copia del #1)

```json
{
  "id": 56, // NFT_ID
  "copy_of": 27
  [...]
}
```
