### ISSUE TITLE
Add geo-location field in NFT's metadata

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#17]
**ToDo**

- [x] Add geo-location field  (provided by chatizalo) in metadata

**Comment by dappsar** [comment]
En chatizalo, ya está disponible la info.

**Comment by gonzageraci** [comment]
- [ ] Modify Model of Mongo. (automating assign to None if not exists)
- [ ] Add param to body "geolocation"
- [ ] Add param to api_tool in GPT model
