### ISSUE TITLE
Improve transactions Logic

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#19]
**ToDo**

- [x] Generate User Operation structure
- [x] Sign the User Operation with the user's EOA
- [x] Send the transaction to the EntryPoint
- [ ] Make the transaction execute properly
- [ ] Integrate the Paymaster to cover the gas fee from the backend's EOA
