### ISSUE TITLE
Add Secret Manager to handle Keys

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#21]
**ToDo**

- [x] Setup of Secret Manager (GCP)
- [x] Incorporation of GCP libraries
- [x] Creation of internal services for R/W in Secret Manager
- [x] Declaration of Secret Manager data in env
- [x] Registration of new back env variables for Secret Manager (GCP)
- [x] R/W of SIGNING_KEY and PRIVATE_KEY with Secret Manager

**Comment by dappsar** [comment]
👋 I spotted in the secret manager that you added CHATIZALO_TOKEN, CHATIZALO_TOKEN_MAIN, and the same for the frontend. So, what’s the plan? 🤔 How are we gonna use these bad boys here?

Remember, the secret manager is like a treasure chest 🏴‍☠️ filled with key-value pairs! The key is the "name of the secret." In our environment, you need to lift the value by name, like a weightlifter at the gym! 💪

You should leave something like:
CHATIZALO_TOKEN_SECRET_KEY 🗝️
FRONTEND_TOKEN_SECRET_KEY 🗝️

Then in GCP, for the dev environment:
CHATIZALO_TOKEN_SECRET_KEY = CHATIZALO_TOKEN 🥳
FRONTEND_TOKEN_SECRET_KEY = FRONTEND_TOKEN 🎉

And in GCP, for the main environment:
CHATIZALO_TOKEN_SECRET_KEY = CHATIZALO_TOKEN_MAIN 🎊
FRONTEND_TOKEN_SECRET_KEY = FRONTEND_TOKEN_MAIN 🎈

By the way, if you’re using nomenclature, let’s stick to it everywhere! Consistency is key, just like that one sock you always wear on laundry day. 🧦 If you put a _dev suffix on a secret name, make sure to do it for all of them:
CHATIZALO_TOKEN_DEV 🚀
CHATIZALO_TOKEN_MAIN 🌟
FRONTEND_TOKEN_DEV 💥
FRONTEND_TOKEN_MAIN 💫

Let’s keep it fun and organized! Happy coding! 😄
