### ISSUE TITLE
Script to upload Images to Internet Computer (ICP) Canister

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#42]
#### Objective:
Develop a script to automate the process of uploading images to an Internet Computer (ICP) canister. The script should handle identity generation, image fetching, and managing the upload process to a specified canister, ensuring error handling and progress tracking.

#### Requirements:
1. **Identity Generation**: 
   - Generate an Ed25519 identity from a mnemonic phrase to authenticate with the ICP network.
   - Validate the mnemonic phrase to ensure it is correctly formatted.
   
2. **Image Download**:
   - Download an image from a provided URL.
   - Convert the image data into a binary buffer.
   - Extract image details, including filename, width, and height.

3. **Image Upload**:
   - Connect to a specified canister using the generated identity.
   - Use the AssetManager to upload the image to a specific folder in the canister.
   - Implement progress tracking for the upload process.
   - Detect if the image already exists and handle accordingly by returning the existing URL.

4. **Error Handling**:
   - Provide clear error messages for issues such as invalid mnemonics, failed downloads, and upload errors.
   - Handle edge cases like duplicate images and network failures.

#### Deliverables:
- A script that takes an image URL, uploads the image to the ICP canister, and returns the URL of the uploaded image.
- The script should include clear logging for progress and potential errors.
- Usage of environment variables (`MNEMONIC`, `CANISTER_ID`) to allow flexibility in configuration.

#### Milestones:
- [ ] Implement mnemonic-based identity generation.
- [ ] Create image downloading functionality.
- [ ] Develop canister upload logic with progress tracking.
- [ ] Test error handling for invalid mnemonics and failed uploads.
- [ ] Provide comprehensive documentation for usage and configuration.

**Comment by dappsar** [comment]
Script desarrollado. 
Se pasó a la funcionalidad de upload de la API.

**Comment by dappsar** [comment]
``js
const axios = require('axios')
const { HttpAgent } = require('@dfinity/agent')
const { AssetManager } = require('@dfinity/assets')
const { Ed25519KeyIdentity } = require('@dfinity/identity')
const crypto = require('crypto')
const bip39 = require('bip39')
require('dotenv').config()

//-----------------------------------------------------------------------------------------------

async function generateIdentityFromMnemonic(mnemonic) {
  const isValidMnemonic = bip39.validateMnemonic(mnemonic)
  if (!isValidMnemonic) {
    throw new Error('La frase semilla es inválida')
  }
  const seed = await bip39.mnemonicToSeed(mnemonic)
  const privateKey = crypto.createHash('sha512').update(seed).digest().slice(0, 32)
  const identity = Ed25519KeyIdentity.fromSecretKey(privateKey)
  return identity
}

const getImageDetails = async (imageUrl) => {
  try {
    const response = await axios.get(imageUrl, { responseType: 'arraybuffer' })
    const imageBuffer = Buffer.from(response.data, 'binary')
    const fileName = imageUrl.split('/').pop()
    const width = 800
    const height = 600
    return { fileName, width, height, imageBuffer }
  } catch (error) {
    throw new Error('Error al descargar la imagen: ' + error.message)
  }
}

const uploadImage = async (imageUrl) => {
  const canisterId = process.env.CANISTER_ID
  const FOLDER_UPLOAD = 'uploads'

  try {
    const identity = await generateIdentityFromMnemonic(process.env.MNEMONIC)
    const principalId = identity.getPrincipal().toText()
    console.log('Principal id:', principalId)

    const agent = new HttpAgent({
      host: 'https://ic0.app',
      identity
    })

    const assetManager = new AssetManager({ canisterId, agent })

    const { fileName, width, height, imageBuffer } = await getImageDetails(imageUrl)
    const batch = assetManager.batch()
    const key = await batch.store(imageBuffer, {
      path: `/${FOLDER_UPLOAD}`,
      fileName: `${fileName}`
    })

    try {
      await batch.commit({
        onProgress: ({ current, total }) => {
          console.log(`Progreso: ${(current / total) * 100}%`)
        }
      })
    } catch (ex) {
      if (ex.message.includes('asset already exists')) {
        console.log(`La imagen ya existe: https://${canisterId}.icp0.io/${FOLDER_UPLOAD}/${fileName}`)
        return {
          success: true,
          message: 'La imagen ya existe.',
          url: `https://${canisterId}.icp0.io/${FOLDER_UPLOAD}/${fileName}`,
          key: fileName,
          fileName,
          width,
          height
        }
      }
      throw ex
    }

    const url = `https://${canisterId}.icp0.io/${FOLDER_UPLOAD}/${fileName}`
    console.log(`Imagen subida con éxito: ${url}`);
    return { success: true, url, key, fileName, width, height }
  } catch (error) {
    console.error('Error al subir la imagen:', error.message)
    return { success: false, error: error.message }
  }
}

//-----------------------------------------------------------------------------------------------


const imageUrl = 'https://images.pexels.com/photos/3756616/pexels-photo-3756616.jpeg'
uploadImage(imageUrl).then(result => {
  console.log('done', result)
})


```
